---
journal: jacsat
type: article
author:
  - name: Ana K. Pitol
    aff: Department of Civil and Environmental Engineering, Imperial College London, United Kingdom
    email: \email{a.pitol-garcia@imperial.ac.uk}

  - name: Timothy R. Julian
    aff: Department of Environmental Microbiology, Eawag, Dubendorf, Switzerland
    alsoaff: Department of Epidemiology and Public Health, Swiss Tropical and Public Health Institute, Basel, Switzerland
    email: \email{tim.julian@eawag.ch}

title:
  formatted: Supporting Information. Risk reduction of SARS-CoV-2 transmission through disinfection of frequently touched surfaces. A Quantitative Microbial Risk Assessment. 
  short: An \textsf{achemso} demo
abbr: IR,NMR,UV
keywords: American Chemical Society, \LaTeX
bibliography: acstest.bib
csl: american-chemical-society.csl
output: rticles::acs_article
includes:
      in_header: preamble.tex
---



## Materials and Methods

### Concentration of virus in the saliva and sputum
Viral loads in the saliva, sputum, or uper respiratory track of symptomatic COVID-19 patients within the first 14 days of symptom onset were used as model input. The viral loads collected from litterature. The number of viruses in the samples were measured using quantitative reverse-transcription polymerase chain reaction (RT-qPCR)  [@Wolfel2020; @Pan2020; @Kim2020; @To2020]. The data were extracted from the figures and is meant to be an approximated number. 

PCR data does not distinguish between infectious and non-infectious virus. No reliable information was found regarding the relationship between gene copy number and infectivity for SARS-CoV-2 [@Jefferson2020]. Therefore, to convert gene copies to infections virus, we used a ratio reported for influenza viruses [@Ip2016].

### Transfer efficiency of virus from hand to mouth
Data on transfer efficiency of a dry inoculum of bacteriophage MS2 from hand to saliva [@Pitol2017] was used as a proxy for transfer efficiency from hand to mucouse membranes. The data used is available at <https://zenodo.org/record/1454505#.Xo3wMZNKjBI>.

### Virus dacay on surface
Modelled as a normal distribution. 
Data obtained from the Suplementary Appendix of [@vanDoremalen2020]. Parameters for steel, using median as mean, and assuming the standard deviation based on the reported confidence intervals. 
The decay rate was calculated as follows: 
$n_x=\frac {ln(2)}{t_\frac{1}{2}}$

### Dose-response 
QMRAwiki, using the from 0.5th, 50th, and 99.5 th percentiles as min, mode, and max of a triangular distribution. 
Data obtained from QMRAwiki http://qmrawiki.org/experiments/sars, Parameter (k) for the exponential model, based on the 2 articles, using 10,000 bootstrap iterations (MLE).
Parameter developed from 2 different studies using 2 different coronaviruses: SARS-CoV and Murine hepatitis virus (MHV-1)
 @DeAlbuquerque2006. A/J mice with MHV-1 virus, intranasal, survival monitored for 21 days. MHV is a common surrogate of human coronaviruses

 @DeDiego2008. 4 groups of the transgenic mice, intranasal, graded doses of rSARS-CoV, survival monitored for 13 days

@Watanabe2010. Combining both dose-response articles to develop the dose-response

### Finger surface area in contact with mouth
Method used by Julian et. all 2018. @Julian2018
Fractional surface area taken from @AuYeung2008 (adult front partial finger)
Average hand surface area taken from EPA 2011 @EPA2011


### Prevalence data 
Data obtained from antibody surveys in different countries. The data is meant to be an estimate of the order of magnitude of the prevalence expected in the population. Estimating prevalence at any given time assuming each person is able to infect for a period of 14 days, Prev [%] =  Seroconversion [%] / (outbreak length [t] /duration of infection [t]). 
Data taken from [@Bendavid2020, @Perez2020, @Pollan2020, @Erikstrup2020, @Filho2020]. Prevalence is between 0.4 (Netherlands) and 1.9 (Geneva). Based on this data, three prevalence scenarios were suggested (0.2,1 and 5%).

### Surface disinfection
Log reduction by disinfection, @Hulkower2011, @Sattar1989 for Chlorine and Ethanol. 
Article             virus (enveloped)     log10 Red     Sanitizer
 __________________  _____________________  __________  ________________________
@Hulkower2011         TGEV (coronavirus)     3.2        Ethanol (70%)
                       MHV (coronavirus)      3.9        Ethanol (70%)
                       TGEV (coronavirus)     0.6        Chlorine bleach (0.06%)  *Concentration too low*
                       MHV (coronavirus)      0.4        Chlorine bleach (0.06%)  *Concentration too low*
 @Sattar1989           HCV-229E(human corona)  >3        Chlorine (0.1%)
                       HCV-229E(human corona)  >3        Chlorine (0.5%) 

 surf_dis <- runif(simNum, 10^3, 10^4)
 
 
### Hand disinfection 
Regarding Hand Hygene. It is recomended by the WHO that [@WHO2010_HandHygene]: An effective alcohol-based hand rub product should contain between 60% and 80% of alcohol.
Log reduction = 4.25 [@Rabenau2005].

### Reduction based on mask 
Method: Henderson apparatus, collison nebulizer (air particles, no droplets)
% Filtration Efficiency (fraction of total virus filtered out by the material) for bacteriophage MS2   
     Min     Material    --   Max    Material
     48.87   Scarf            89.52  Surgical Mask
     
     


## References


